/* All copy lives here. Strings keyed by language. */
export const CONTENT = {
  en: {
    nav: {
      profile: "Profile",
      pillars: "Capabilities",
      work: "Work",
      method: "Method",
      contact: "Contact",
    },
    hero: {
      pills: ["SENIOR", "DIGITAL MARKETING", "MAR-TECH"],
      title: "Portfolio.",
      subtitle: "2026 Edition",
      name: "Le Hoang Tuan Anh",
      role: "Senior Digital Marketing & Mar-Tech Specialist",
      lead: "5+ years operating multi-channel advertising and building measurement systems — from Google Ads, Meta Ads, TikTok Ads to GA4, GTM, Server-side Tracking, Looker Studio.",
      kpis: [
        { v: "5", u: "+ YRS", l: "Operating" },
        { v: "6", u: "", l: "Case Studies" },
        { v: "3.04", u: "B", l: "VND Revenue" },
      ],
      scroll: "SCROLL",
    },
    marquee: ["DATA", "SYSTEM", "SCALE", "MEASURED", "OPTIMIZED", "SCALABLE"],
    profile: {
      eyebrow: "[ 00 ] PROFILE",
      title: "Professional Profile.",
      lead: "5+ years operating Digital Marketing across diverse industries — from furniture, building materials, home design to retail chains & E-commerce. Focused on measurement engineering, conversion optimization and building scalable marketing systems.",
      quote: "Not just running ads — I build marketing systems that are measurable, optimizable, and scalable. Every budget dollar has a reason; every decision is data-driven.",
      stats: [
        { v: "55", u: "%", l: "of total revenue from Paid Media at Trung Son Care" },
        { v: "9.85", u: "×", l: "ROAS — average across the peak month" },
        { v: "168", u: "", l: "qualified leads from Google Ads at Noi That Mien Tay" },
        { v: "0", u: "", l: "SERP position (featured snippet) for Van Nam roof tiles" },
      ],
      photoNote: "Drop portrait photo here",
    },
    pillars: {
      eyebrow: "[ 01 ] THREE CAPABILITY PILLARS",
      title: "Data. System. Scale.",
      sub: "The operating model behind every case study in this portfolio.",
      items: [
        {
          num: "01 / DATA",
          h: "Data",
          p: "Build the measurement layer first. Track every signal that matters, store it where it can be queried, visualize the trade-offs leadership needs to see.",
          tags: ["GA4", "Looker Studio", "BigQuery", "Server-side"],
        },
        {
          num: "02 / SYSTEM",
          h: "System",
          p: "Tag what cannot be tagged. Restore signal lost to iOS 14.5, cookie loss, ad-blockers — via GTM Server, CAPI, Enhanced Conversions, deduplicated events.",
          tags: ["GTM", "CAPI", "Enhanced Conv.", "CRO"],
        },
        {
          num: "03 / SCALE",
          h: "Scale",
          p: "Once measurement is honest and tags are clean, scale spend with confidence. Multi-channel ops, SEO, CRM, performance review cadence.",
          tags: ["Paid Media", "SEO", "CRM", "Performance Ops"],
        },
      ],
    },
    cases: {
      eyebrow: "[ 02 ] CASE STUDIES",
      title: "Selected Work.",
      sub: "Six engagements. Every number pulled directly from dashboards I personally operated.",
      list: [
        {
          idx: "01",
          yr: "2024 — 2026",
          ind: "Pharmacy Retail · Mekong Delta",
          name: "Trung Son Care",
          feature: true,
          summary: "Started remotely in 2024, then took over Mar-Tech full-time from 09/2025. Rebuilt the entire measurement layer on GTM Server (Stape.io) and deduplicated events across Google + Meta + TikTok via Enhanced Conversions + CAPI. Paid Media now drives 55% of revenue with a fully attributable funnel.",
          kpis: [
            { v: "9.85", u: "×", l: "Peak-month ROAS" },
            { v: "3.04", u: "B", l: "Revenue (VND)" },
            { v: "−58.6", u: "%", l: "CPA Reduction" },
            { v: "55", u: "%", l: "Paid Media Share" },
          ],
          tags: ["GTM Server", "Stape.io", "CAPI", "Enhanced Conv.", "GA4", "Looker"],
          chartTitle: "ROAS · E-Commerce Channel · APR–DEC 2025",
          chart: "ecm-roas",
        },
        {
          idx: "02",
          yr: "2023 — 2024",
          ind: "Home Design & Construction · Side project",
          name: "ENOCOM — Home design & furniture manufacturing",
          summary: "Two Google Ads campaigns running in parallel: one sourcing residential design briefs, the other sourcing furniture manufacturing orders. With a 3–6 month decision cycle and contracts worth 500M–2B VND, lead quality beats lead volume — a multi-step form qualifies budget, floor area and start date right on the landing page. Ad Strength rated \"Excellent\".",
          kpis: [
            { v: "75", u: "%", l: "Lead → Contract" },
            { v: "3", u: "/4", l: "Contracts Signed" },
            { v: "2", u: "", l: "Parallel Campaigns" },
          ],
          tags: ["Google Ads", "Search", "Lead Gen", "Landing Page"],
          chartTitle: "Lead to signed contract",
          chart: "enocom-funnel",
        },
        {
          idx: "03",
          yr: "2024",
          ind: "Premium Interior Design · Side project",
          name: "ICOM Design — Meta Instant Experience",
          summary: "Built full-screen Instant Experience flows on Meta for a premium interior brand. Furniture has to be shown, not described — the full-screen format held viewers 3.5× longer than a single image, and conversations closed inside Messenger without leaving the platform.",
          kpis: [
            { v: "3.5", u: "×", l: "View Time" },
            { v: "28", u: "", l: "Conversations" },
            { v: "81.839", u: "đ", l: "Cost / Conversion" },
          ],
          tags: ["Meta Ads", "Instant Experience", "Messenger", "Creative"],
          chartTitle: "View time · Single image vs Instant Experience",
          chart: "view-time",
        },
        {
          idx: "04",
          yr: "2023 — 2024",
          ind: "Building Materials · Roof Tiles · Side project",
          name: "Van Nam — Top 0 SERP, ROI 300%",
          summary: "SEO + Google Ads dual track for the roof tile category. Captured Top 0 (featured snippet) on head terms and Top 1 in Shopping. ROAS 168% delivered ROI 300% net.",
          kpis: [
            { v: "300", u: "%", l: "ROI" },
            { v: "168", u: "%", l: "ROAS" },
            { v: "0", u: "", l: "SERP (snippet)" },
            { v: "1", u: "", l: "Shop Position" },
          ],
          tags: ["SEO", "Google Ads", "Shopping", "Featured Snippet"],
          chartTitle: "Rank progression",
          chart: "rank",
        },
        {
          idx: "05",
          yr: "2023 — 2024",
          ind: "Furniture · Water tanks & solar heaters · Side project",
          name: "Noi That Mien Tay — 168 leads on Google Ads",
          summary: "Google Search plus Performance Max for water tanks and solar water heaters. A single account structure covering three very different buyer groups — contractors, dealers and homeowners — each with its own creative set and landing page. Head terms hit a 10/10 Quality Score, cutting CPC by 40–60%.",
          kpis: [
            { v: "168", u: "", l: "Leads" },
            { v: "10", u: "/10", l: "Quality Score" },
            { v: "3", u: "", l: "Buyer Personas" },
          ],
          tags: ["Google Ads", "Search", "Performance Max", "Quality Score 10/10"],
          chartTitle: "168 leads · split by buyer persona",
          chart: "persona",
        },
        {
          idx: "06",
          yr: "2023 — 2024",
          ind: "Side Projects",
          name: "Three websites — built & operated",
          summary: "Designed, built and operated three brand websites end-to-end — ngoivannam.vn, noithatmientay.vn and icomdesign.com — from copywriting and information architecture through to deployment, GA4/GTM wiring and content cadence. Lighthouse 88–94, LCP under 2.5s across all three.",
          kpis: [
            { v: "3", u: "", l: "Sites Live" },
            { v: "94", u: "", l: "Best Lighthouse" },
            { v: "100", u: "%", l: "Self-Operated" },
          ],
          tags: ["WordPress", "Webflow", "GA4", "GTM", "Copy", "IA"],
          chartTitle: null,
          chart: null,
        },
      ],
    },
    method: {
      eyebrow: "[ 03 ] METHODOLOGY",
      title: "Data-Driven Marketing.",
      sub: "Every client engagement runs the same four-step loop. Measurement first, scale last.",
      steps: [
        { step: "STEP 01", h: "Measure", d: "GA4 + GTM Server. Define events that map to revenue. Audit existing tags." },
        { step: "STEP 02", h: "Restore", d: "CAPI, Enhanced Conversions, server-side dedupe. Recover signal lost to iOS / cookie loss." },
        { step: "STEP 03", h: "Optimize", d: "Bid strategy review, audience refinement, CRO on landing pages. Tighten the funnel." },
        { step: "STEP 04", h: "Scale", d: "Confident spend across Google + Meta + TikTok. Looker dashboards for weekly review." },
      ],
    },
    highlights: {
      eyebrow: "[ 04 ] HIGHLIGHTS",
      title: "Three numbers that matter.",
      sub: "The three results I would point to first — each one pulled from a dashboard I ran myself.",
      items: [
        { tag: "TRUNG SON CARE", v: "9.85", u: "× ROAS", l: "3.04B Revenue · CPA −58.6%" },
        { tag: "NOI THAT MIEN TAY", v: "168", u: "Leads", l: "Quality Score 10/10 · CPC −40–60%" },
        { tag: "VAN NAM", v: "300", u: "% ROI", l: "Top 0 Snippet · Top 1 Shopping" },
      ],
    },
    skills: {
      eyebrow: "[ 05 ] CAPABILITIES",
      title: "Tools & Stack.",
      sub: "Operating proficiency. Years in production, not just certifications.",
      groups: [
        { cat: "Data", items: [["GA4", 0.95], ["Looker Studio", 0.95], ["BigQuery", 0.7], ["GTM Server", 0.9]] },
        { cat: "System", items: [["GTM", 0.95], ["Meta CAPI", 0.9], ["Enhanced Conv.", 0.9], ["Stape.io", 0.85]] },
        { cat: "Scale", items: [["Google Ads", 0.95], ["Meta Ads", 0.95], ["TikTok Ads", 0.85], ["SEO Ops", 0.85]] },
        { cat: "Build", items: [["WordPress", 0.85], ["Webflow", 0.75], ["HTML/CSS", 0.8], ["Copywriting", 0.85]] },
      ],
    },
    contact: {
      eyebrow: "[ 06 ] CONTACT",
      title: "Let's talk.",
      lead: "Every number in this portfolio comes directly from dashboards I personally operated. Open for a screen-share demo at interview time.",
      cards: [
        { lbl: "PHONE · ZALO", val: "0886.148.937", sub: "Fast reply · Same Zalo number" },
        { lbl: "EMAIL", val: "sandrabruh@proton.me", sub: "Response within 24 hours" },
        { lbl: "LOCATION", val: "Can Tho · HCMC", sub: "Fulltime Can Tho · Remote flexible" },
        { lbl: "PROFILE", val: "LinkedIn", sub: "Open to connect & discuss" },
      ],
      cta: "Open for next role · Available now",
    },
    footer: {
      tag: "PORTFOLIO 2026 · v3.0",
      quote: "Marketing isn't art. It's the engineering of numbers.",
      meta: ["LE HOANG TUAN ANH", "UPDATED · JUL 2026", "DATA · SYSTEM · SCALE"],
    },
  },

  vi: {
    nav: {
      profile: "Hồ sơ",
      pillars: "Năng lực",
      work: "Dự án",
      method: "Cách làm",
      contact: "Liên hệ",
    },
    hero: {
      pills: ["SENIOR", "DIGITAL MARKETING", "MAR-TECH"],
      title: "Portfolio.",
      subtitle: "Bản 2026",
      name: "Lê Hoàng Tuấn Anh",
      role: "Senior Digital Marketing & Mar-Tech Specialist",
      lead: "Hơn 5 năm chạy quảng cáo đa kênh và xây hệ thống đo lường cho doanh nghiệp — từ Google Ads, Meta Ads, TikTok Ads đến GA4, GTM, Server-side Tracking và Looker Studio.",
      kpis: [
        { v: "5", u: "+ NĂM", l: "Kinh nghiệm" },
        { v: "6", u: "", l: "Dự án tiêu biểu" },
        { v: "3.04", u: "Tỷ", l: "Doanh thu (VNĐ)" },
      ],
      scroll: "CUỘN XUỐNG",
    },
    marquee: ["DỮ LIỆU", "HỆ THỐNG", "MỞ RỘNG", "ĐO LƯỜNG", "TỐI ƯU", "BỀN VỮNG"],
    profile: {
      eyebrow: "[ 00 ] HỒ SƠ",
      title: "Hồ sơ chuyên môn.",
      lead: "Hơn 5 năm làm Digital Marketing qua nhiều ngành — từ nội thất, vật liệu xây dựng, thiết kế nhà đến chuỗi bán lẻ và thương mại điện tử. Tôi tập trung vào ba việc: đo lường cho đúng, tăng tỷ lệ chuyển đổi và xây hệ thống marketing có thể mở rộng.",
      quote: "Tôi không chỉ chạy quảng cáo — tôi xây hệ thống marketing đo lường được, tối ưu được và mở rộng được. Mỗi đồng ngân sách đều có lý do, mỗi quyết định đều dựa trên dữ liệu.",
      stats: [
        { v: "55", u: "%", l: "tổng doanh thu đến từ quảng cáo tại Trung Sơn Care" },
        { v: "9.85", u: "×", l: "ROAS trung bình của tháng cao nhất" },
        { v: "168", u: "", l: "khách hàng tiềm năng từ Google Ads — Nội Thất Miền Tây" },
        { v: "0", u: "", l: "vị trí Google — chiếm Featured Snippet cho ngói Vân Nam" },
      ],
      photoNote: "Thả ảnh chân dung vào đây",
    },
    pillars: {
      eyebrow: "[ 01 ] BA TRỤ CỘT NĂNG LỰC",
      title: "Dữ liệu. Hệ thống. Mở rộng.",
      sub: "Đây là cách tôi làm việc trong mọi dự án bên dưới.",
      items: [
        {
          num: "01 / DATA",
          h: "Dữ liệu",
          p: "Dựng hệ thống đo lường trước tiên. Ghi nhận đầy đủ hành vi quan trọng của khách hàng, lưu vào nơi có thể tra cứu bất cứ lúc nào, rồi biến dữ liệu đó thành báo cáo mà ban lãnh đạo nhìn vào là ra quyết định được.",
          tags: ["GA4", "Looker Studio", "BigQuery", "Server-side"],
        },
        {
          num: "02 / SYSTEM",
          h: "Hệ thống",
          p: "Lấy lại dữ liệu tưởng như đã mất. iOS 14.5, việc chặn cookie và ad-block khiến quảng cáo mất dấu khách hàng — GTM Server, CAPI và Enhanced Conversions nối lại đường dữ liệu đó, đồng thời loại bỏ những đơn bị đếm trùng.",
          tags: ["GTM", "CAPI", "Enhanced Conv.", "CRO"],
        },
        {
          num: "03 / SCALE",
          h: "Mở rộng",
          p: "Khi số liệu đã chuẩn, tăng ngân sách không còn là đánh cược. Chạy song song nhiều kênh, kết hợp SEO và CRM, rà soát hiệu quả theo lịch cố định mỗi tuần.",
          tags: ["Paid Media", "SEO", "CRM", "Performance Ops"],
        },
      ],
    },
    cases: {
      eyebrow: "[ 02 ] DỰ ÁN",
      title: "Dự án tiêu biểu.",
      sub: "Sáu dự án. Mọi con số đều lấy trực tiếp từ dashboard do tôi tự vận hành.",
      list: [
        {
          idx: "01",
          yr: "2024 — 2026",
          ind: "Bán lẻ dược phẩm · ĐBSCL",
          name: "Trung Sơn Care",
          feature: true,
          summary: "Bắt đầu hỗ trợ từ xa từ 2024, chính thức phụ trách Mar-Tech từ 09/2025. Xây lại toàn bộ hệ thống đo lường bằng GTM Server (Stape.io), lọc trùng dữ liệu chuyển đổi giữa Google, Meta và TikTok qua Enhanced Conversions và CAPI. Kết quả: quảng cáo đóng góp 55% doanh thu và mọi đơn hàng đều truy được về đúng kênh đã tạo ra nó.",
          kpis: [
            { v: "9.85", u: "×", l: "ROAS tháng cao nhất" },
            { v: "3.04", u: "Tỷ", l: "Doanh thu (VNĐ)" },
            { v: "−58.6", u: "%", l: "Chi phí mỗi đơn" },
            { v: "55", u: "%", l: "Doanh thu từ ads" },
          ],
          tags: ["GTM Server", "Stape.io", "CAPI", "Enhanced Conv.", "GA4", "Looker"],
          chartTitle: "ROAS · Kênh thương mại điện tử · 04–12/2025",
          chart: "ecm-roas",
        },
        {
          idx: "02",
          yr: "2023 — 2024",
          ind: "Tư vấn & thiết kế xây dựng · Dự án ngoài",
          name: "ENOCOM — Thiết kế nhà & gia công nội thất",
          summary: "Hai chiến dịch Google Ads chạy song song: một tìm khách thiết kế nhà ở, một tìm đơn gia công nội thất. Ngành này có chu kỳ ra quyết định 3–6 tháng và hợp đồng từ 500 triệu đến 2 tỷ, nên chất lượng lead quan trọng hơn số lượng — form nhiều bước lọc sẵn ngân sách, diện tích và thời điểm khởi công ngay trên landing page. Mẫu quảng cáo đạt Ad Strength mức \"Rất tốt\".",
          kpis: [
            { v: "75", u: "%", l: "Lead thành hợp đồng" },
            { v: "3", u: "/4", l: "Hợp đồng đã ký" },
            { v: "2", u: "", l: "Chiến dịch song song" },
          ],
          tags: ["Google Ads", "Search", "Lead Gen", "Landing Page"],
          chartTitle: "Từ lead đến hợp đồng",
          chart: "enocom-funnel",
        },
        {
          idx: "03",
          yr: "2024",
          ind: "Thiết kế nội thất cao cấp · Dự án ngoài",
          name: "ICOM Design — Meta Instant Experience",
          summary: "Dựng luồng Instant Experience toàn màn hình trên Meta cho thương hiệu nội thất cao cấp. Nội thất là thứ phải cho khách xem chứ không thể tả — định dạng full-screen giữ người xem lâu gấp 3.5 lần so với ảnh đơn, và chốt đơn ngay trong khung chat Messenger mà không cần rời Facebook.",
          kpis: [
            { v: "3.5", u: "×", l: "Thời gian xem" },
            { v: "28", u: "", l: "Cuộc trò chuyện" },
            { v: "81.839", u: "đ", l: "Chi phí / chuyển đổi" },
          ],
          tags: ["Meta Ads", "Instant Experience", "Messenger", "Creative"],
          chartTitle: "Thời gian xem · Ảnh đơn vs Instant Experience",
          chart: "view-time",
        },
        {
          idx: "04",
          yr: "2023 — 2024",
          ind: "Vật liệu xây dựng · Ngói lợp · Dự án ngoài",
          name: "Vân Nam — Top 0 Google, lợi nhuận 300%",
          summary: "Làm song song SEO và Google Ads cho ngành ngói lợp. Chiếm Top 0 (Featured Snippet) ở từ khóa chính và Top 1 mục Shopping. ROAS 168% quy ra lợi nhuận ròng gấp 3 lần chi phí bỏ ra.",
          kpis: [
            { v: "300", u: "%", l: "Lợi nhuận / đầu tư" },
            { v: "168", u: "%", l: "ROAS" },
            { v: "0", u: "", l: "Vị trí Google" },
            { v: "1", u: "", l: "Vị trí Shopping" },
          ],
          tags: ["SEO", "Google Ads", "Shopping", "Featured Snippet"],
          chartTitle: "Thứ hạng từ khóa",
          chart: "rank",
        },
        {
          idx: "05",
          yr: "2023 — 2024",
          ind: "Nội thất · Bồn nước & NLMT · Dự án ngoài",
          name: "Nội Thất Miền Tây — 168 leads Google Ads",
          summary: "Google Search kết hợp Performance Max cho bồn nước và máy nước nóng năng lượng mặt trời. Một cấu trúc tài khoản phủ cùng lúc ba nhóm khách rất khác nhau — thầu thợ, đại lý và chủ nhà — mỗi nhóm một bộ mẫu quảng cáo và landing page riêng. Từ khóa chính đạt điểm chất lượng 10/10, kéo CPC giảm 40–60%.",
          kpis: [
            { v: "168", u: "", l: "Khách hàng tiềm năng" },
            { v: "10", u: "/10", l: "Điểm chất lượng" },
            { v: "3", u: "", l: "Nhóm khách hàng" },
          ],
          tags: ["Google Ads", "Search", "Performance Max", "Quality Score 10/10"],
          chartTitle: "168 leads · Phân bổ theo nhóm khách",
          chart: "persona",
        },
        {
          idx: "06",
          yr: "2023 — 2024",
          ind: "Dự án cá nhân",
          name: "Ba website — tự xây và vận hành",
          summary: "Tự làm trọn gói ba website thương hiệu — ngoivannam.vn, noithatmientay.vn và icomdesign.com: từ viết nội dung, sắp xếp cấu trúc trang, đưa lên hosting, gắn GA4 và GTM cho tới lên lịch đăng bài. Điểm Lighthouse 88–94, thời gian tải nội dung chính đều dưới 2.5 giây.",
          kpis: [
            { v: "3", u: "", l: "Website đang chạy" },
            { v: "94", u: "", l: "Lighthouse cao nhất" },
            { v: "100", u: "%", l: "Tự vận hành" },
          ],
          tags: ["WordPress", "Webflow", "GA4", "GTM", "Copy", "IA"],
          chartTitle: null,
          chart: null,
        },
      ],
    },
    method: {
      eyebrow: "[ 03 ] CÁCH LÀM",
      title: "Marketing dựa trên dữ liệu.",
      sub: "Mọi dự án đều đi qua cùng một quy trình 4 bước: đo lường trước, mở rộng sau.",
      steps: [
        { step: "BƯỚC 01", h: "Đo lường", d: "Cài GA4 và GTM Server. Xác định đúng những hành vi tạo ra doanh thu, rà soát lại toàn bộ tag đang chạy." },
        { step: "BƯỚC 02", h: "Khôi phục", d: "Dùng CAPI, Enhanced Conversions và xử lý phía máy chủ để lấy lại dữ liệu bị mất do iOS và trình duyệt chặn cookie." },
        { step: "BƯỚC 03", h: "Tối ưu", d: "Rà lại chiến lược giá thầu, siết lại tệp khách hàng và cải thiện landing page để tăng tỷ lệ chuyển đổi." },
        { step: "BƯỚC 04", h: "Mở rộng", d: "Tăng ngân sách trên Google, Meta và TikTok. Theo dõi bằng dashboard Looker và họp rà soát hàng tuần." },
      ],
    },
    highlights: {
      eyebrow: "[ 04 ] ĐIỂM NHẤN",
      title: "Ba con số đáng nhớ nhất.",
      sub: "Nếu chỉ được chọn ba kết quả để nói về năng lực của tôi, tôi chọn ba con số này.",
      items: [
        { tag: "TRUNG SƠN CARE", v: "9.85", u: "× ROAS", l: "3.04 tỷ doanh thu · Chi phí mỗi đơn giảm 58.6%" },
        { tag: "NỘI THẤT MIỀN TÂY", v: "168", u: "leads", l: "Điểm chất lượng 10/10 · CPC giảm 40–60%" },
        { tag: "VÂN NAM", v: "300", u: "% lợi nhuận", l: "Top 0 Google · Top 1 Shopping" },
      ],
    },
    skills: {
      eyebrow: "[ 05 ] NĂNG LỰC",
      title: "Công cụ & Nền tảng.",
      sub: "Mức độ thành thạo từ thực chiến — tích lũy qua nhiều năm vận hành thật, không chỉ từ chứng chỉ.",
      groups: [
        { cat: "Dữ liệu", items: [["GA4", 0.95], ["Looker Studio", 0.95], ["BigQuery", 0.7], ["GTM Server", 0.9]] },
        { cat: "Hệ thống", items: [["GTM", 0.95], ["Meta CAPI", 0.9], ["Enhanced Conv.", 0.9], ["Stape.io", 0.85]] },
        { cat: "Mở rộng", items: [["Google Ads", 0.95], ["Meta Ads", 0.95], ["TikTok Ads", 0.85], ["SEO Ops", 0.85]] },
        { cat: "Xây dựng", items: [["WordPress", 0.85], ["Webflow", 0.75], ["HTML/CSS", 0.8], ["Copywriting", 0.85]] },
      ],
    },
    contact: {
      eyebrow: "[ 06 ] LIÊN HỆ",
      title: "Cùng trao đổi.",
      lead: "Mọi con số trong portfolio đều lấy trực tiếp từ dashboard do tôi vận hành. Tôi sẵn sàng chia sẻ màn hình để minh họa cụ thể khi phỏng vấn.",
      cards: [
        { lbl: "ĐIỆN THOẠI · ZALO", val: "0886.148.937", sub: "Phản hồi nhanh · Zalo cùng số" },
        { lbl: "EMAIL", val: "sandrabruh@proton.me", sub: "Phản hồi trong vòng 24 giờ" },
        { lbl: "KHU VỰC", val: "Cần Thơ · TP.HCM", sub: "Làm việc tại Cần Thơ · Nhận remote" },
        { lbl: "HỒ SƠ", val: "LinkedIn", sub: "Kết nối và trao đổi thêm" },
      ],
      cta: "Sẵn sàng nhận vị trí mới · Có thể bắt đầu ngay",
    },
    footer: {
      tag: "PORTFOLIO 2026 · v3.0",
      quote: "Marketing không phải là nghệ thuật. Đó là kỹ thuật của những con số.",
      meta: ["LE HOANG TUAN ANH", "CẬP NHẬT · 7/2026", "DATA · SYSTEM · SCALE"],
    },
  },
};
