/* All copy lives here. Strings keyed by language. */
export const CONTENT = {
  en: {
    nav: {
      profile: "Profile",
      pillars: "Capabilities",
      work: "Work",
      method: "Method",
      contact: "Contact",
    },
    hero: {
      pills: ["SENIOR", "DIGITAL MARKETING", "MAR-TECH"],
      title: "Portfolio.",
      subtitle: "2026 Edition",
      name: "Le Hoang Tuan Anh",
      role: "Senior Digital Marketing & Mar-Tech Specialist",
      lead: "5+ years operating multi-channel advertising and building measurement systems — from Google Ads, Meta Ads, TikTok Ads to GA4, GTM, Server-side Tracking, Looker Studio.",
      kpis: [
        { v: "5", u: "+ YRS", l: "Operating" },
        { v: "6", u: "", l: "Case Studies" },
        { v: "3.04", u: "B", l: "VND Revenue" },
      ],
      scroll: "SCROLL",
    },
    marquee: ["DATA", "SYSTEM", "SCALE", "MEASURED", "OPTIMIZED", "SCALABLE"],
    profile: {
      eyebrow: "[ 00 ] PROFILE",
      title: "Professional\nProfile.",
      lead: "5+ years operating Digital Marketing across diverse industries — from furniture, building materials, home design to retail chains & E-commerce. Focused on measurement engineering, conversion optimization and building scalable marketing systems.",
      quote: "Not just running ads — I build marketing systems that are measurable, optimizable, and scalable. Every budget dollar has a reason; every decision is data-driven.",
      stats: [
        { v: "55", u: "%", l: "of total revenue from Paid Media at Trung Son Care" },
        { v: "9.85", u: "×", l: "ROAS — best campaign performance" },
        { v: "168", u: "", l: "qualified leads / 30 days at ENOCOM" },
        { v: "0", u: "", l: "SERP position (featured snippet) for Van Nam roof tiles" },
      ],
      photoNote: "Drop portrait photo here",
    },
    pillars: {
      eyebrow: "[ 01 ] THREE CAPABILITY PILLARS",
      title: "Data. System. Scale.",
      sub: "The operating model behind every case study in this portfolio.",
      items: [
        {
          num: "01 / DATA",
          h: "Data",
          p: "Build the measurement layer first. Track every signal that matters, store it where it can be queried, visualize the trade-offs leadership needs to see.",
          tags: ["GA4", "Looker Studio", "BigQuery", "Server-side"],
        },
        {
          num: "02 / SYSTEM",
          h: "System",
          p: "Tag what cannot be tagged. Restore signal lost to iOS 14.5, cookie loss, ad-blockers — via GTM Server, CAPI, Enhanced Conversions, deduplicated events.",
          tags: ["GTM", "CAPI", "Enhanced Conv.", "CRO"],
        },
        {
          num: "03 / SCALE",
          h: "Scale",
          p: "Once measurement is honest and tags are clean, scale spend with confidence. Multi-channel ops, SEO, CRM, performance review cadence.",
          tags: ["Paid Media", "SEO", "CRM", "Performance Ops"],
        },
      ],
    },
    cases: {
      eyebrow: "[ 02 ] CASE STUDIES",
      title: "Selected Work.",
      sub: "Six engagements. Every number pulled directly from dashboards I personally operated.",
      list: [
        {
          idx: "01",
          yr: "2024 — 2025",
          ind: "Pharmacy Retail · Mekong Delta",
          name: "Trung Son Care",
          feature: true,
          summary: "Rebuilt the entire measurement layer on GTM Server (Stape.io), deduplicated events across Google + Meta + TikTok via Enhanced Conversion + CAPI. Paid Media now drives 55% of revenue with a fully attributable funnel.",
          kpis: [
            { v: "9.85", u: "×", l: "ROAS Peak" },
            { v: "3.04", u: "B", l: "Revenue (VND)" },
            { v: "−58.6", u: "%", l: "CPA Reduction" },
            { v: "55", u: "%", l: "Paid Media Share" },
          ],
          tags: ["GTM Server", "Stape.io", "CAPI", "Enhanced Conv.", "GA4", "Looker"],
          chartTitle: "ROAS · 14-month trend",
          chart: "roas",
        },
        {
          idx: "02",
          yr: "2023 — 2024",
          ind: "Home Design & Construction",
          name: "ENOCOM — 168 Leads on Google Ads",
          summary: "Search + Performance Max for water tanks and solar water heaters. Quality Score 10/10 across head terms; 168 qualified leads converted at 75% close rate over 30 days.",
          kpis: [
            { v: "168", u: "", l: "Leads / 30d" },
            { v: "75", u: "%", l: "Close Rate" },
            { v: "10", u: "/10", l: "Quality Score" },
            { v: "3.2", u: "×", l: "ROAS" },
          ],
          tags: ["Google Ads", "Search", "Performance Max", "Lead Gen"],
          chartTitle: "Conversions vs Cost",
          chart: "leads",
        },
        {
          idx: "03",
          yr: "2024",
          ind: "Premium Interior Design",
          name: "ICOM Design — Meta Instant Experience",
          summary: "Built mobile-native Instant Experience flows on Meta for premium interior design briefs. Catalog Remarketing + Advantage+ Shopping running in parallel with Messenger Conversions.",
          kpis: [
            { v: "4.1", u: "×", l: "ROAS" },
            { v: "−42", u: "%", l: "CPL" },
            { v: "8.7", u: "%", l: "CTR" },
          ],
          tags: ["Meta Ads", "Instant Experience", "Advantage+", "Catalog"],
          chartTitle: "Funnel · Reach → Lead",
          chart: "funnel",
        },
        {
          idx: "04",
          yr: "2023 — 2024",
          ind: "Building Materials · Roof Tiles",
          name: "Van Nam — Top 0 SERP, ROI 300%",
          summary: "SEO + Google Ads dual track for the roof tile category. Captured Top 0 (featured snippet) on head terms and Top 1 in Shopping. ROAS 168% delivered ROI 300% net.",
          kpis: [
            { v: "300", u: "%", l: "ROI" },
            { v: "168", u: "%", l: "ROAS" },
            { v: "0", u: "", l: "SERP (snippet)" },
            { v: "1", u: "", l: "Shop Position" },
          ],
          tags: ["SEO", "Google Ads", "Shopping", "Featured Snippet"],
          chartTitle: "Rank progression",
          chart: "rank",
        },
        {
          idx: "05",
          yr: "2023 — 2024",
          ind: "Side Projects",
          name: "Three websites — built & operated",
          summary: "Designed, built and operated three brand websites end-to-end — from copywriting and information architecture through to deployment, GA4/GTM wiring and content cadence.",
          kpis: [
            { v: "3", u: "", l: "Sites Live" },
            { v: "100", u: "%", l: "Self-Operated" },
          ],
          tags: ["WordPress", "Webflow", "GA4", "GTM", "Copy", "IA"],
          chartTitle: null,
          chart: null,
        },
      ],
    },
    method: {
      eyebrow: "[ 03 ] METHODOLOGY",
      title: "Data-Driven Marketing.",
      sub: "Every client engagement runs the same four-step loop. Measurement first, scale last.",
      steps: [
        { step: "STEP 01", h: "Measure", d: "GA4 + GTM Server. Define events that map to revenue. Audit existing tags." },
        { step: "STEP 02", h: "Restore", d: "CAPI, Enhanced Conversions, server-side dedupe. Recover signal lost to iOS / cookie loss." },
        { step: "STEP 03", h: "Optimize", d: "Bid strategy review, audience refinement, CRO on landing pages. Tighten the funnel." },
        { step: "STEP 04", h: "Scale", d: "Confident spend across Google + Meta + TikTok. Looker dashboards for weekly review." },
      ],
    },
    highlights: {
      eyebrow: "[ 04 ] HIGHLIGHTS",
      title: "Three numbers.",
      sub: "If the rest of the portfolio went unread, these would be the ones to remember.",
      items: [
        { tag: "TRUNG SON CARE", v: "9.85", u: "× ROAS", l: "3.04B Revenue · CPA −58.6%" },
        { tag: "ENOCOM", v: "75", u: "% Close", l: "Quality Score 10/10 · 168 Leads" },
        { tag: "VAN NAM", v: "300", u: "% ROI", l: "Top 0 Snippet · Top 1 Shopping" },
      ],
    },
    skills: {
      eyebrow: "[ 05 ] CAPABILITIES",
      title: "Tools & Stack.",
      sub: "Operating proficiency. Years in production, not just certifications.",
      groups: [
        { cat: "Data", items: [["GA4", 0.95], ["Looker Studio", 0.95], ["BigQuery", 0.7], ["GTM Server", 0.9]] },
        { cat: "System", items: [["GTM", 0.95], ["Meta CAPI", 0.9], ["Enhanced Conv.", 0.9], ["Stape.io", 0.85]] },
        { cat: "Scale", items: [["Google Ads", 0.95], ["Meta Ads", 0.95], ["TikTok Ads", 0.85], ["SEO Ops", 0.85]] },
        { cat: "Build", items: [["WordPress", 0.85], ["Webflow", 0.75], ["HTML/CSS", 0.8], ["Copywriting", 0.85]] },
      ],
    },
    contact: {
      eyebrow: "[ 06 ] CONTACT",
      title: "Let's\ntalk.",
      lead: "Every number in this portfolio comes directly from dashboards I personally operated. Open for a screen-share demo at interview time.",
      cards: [
        { lbl: "PHONE · ZALO", val: "0886.148.937", sub: "Fast reply · Same Zalo number" },
        { lbl: "EMAIL", val: "sandrabruh@proton.me", sub: "Response within 24 hours" },
        { lbl: "LOCATION", val: "Can Tho · HCMC", sub: "Fulltime Can Tho · Remote flexible" },
        { lbl: "PROFILE", val: "LinkedIn", sub: "Open to connect & discuss" },
      ],
      cta: "Open for next role · Available May 2026",
    },
    footer: {
      tag: "PORTFOLIO 2026 · v3.0",
      quote: "Marketing isn't art. It's the engineering of numbers.",
      meta: ["LE HOANG TUAN ANH", "UPDATED · MAY 2026", "DATA · SYSTEM · SCALE"],
    },
  },

  vi: {
    nav: {
      profile: "Hồ sơ",
      pillars: "Năng lực",
      work: "Dự án",
      method: "Phương pháp",
      contact: "Liên hệ",
    },
    hero: {
      pills: ["SENIOR", "DIGITAL MARKETING", "MAR-TECH"],
      title: "Portfolio.",
      subtitle: "Bản 2026",
      name: "Lê Hoàng Tuấn Anh",
      role: "Senior Digital Marketing & Mar-Tech Specialist",
      lead: "5+ năm vận hành quảng cáo đa kênh và xây hệ thống đo lường — từ Google Ads, Meta Ads, TikTok Ads tới GA4, GTM, Server-side Tracking, Looker Studio.",
      kpis: [
        { v: "5", u: "+ NĂM", l: "Vận hành" },
        { v: "6", u: "", l: "Case Studies" },
        { v: "3.04", u: "Tỷ", l: "Doanh thu VND" },
      ],
      scroll: "CUỘN",
    },
    marquee: ["DỮ LIỆU", "HỆ THỐNG", "MỞ RỘNG", "ĐO LƯỜNG", "TỐI ƯU", "BỀN VỮNG"],
    profile: {
      eyebrow: "[ 00 ] HỒ SƠ",
      title: "Hồ sơ\nchuyên môn.",
      lead: "5+ năm vận hành Digital Marketing qua nhiều ngành — từ nội thất, vật liệu xây dựng, thiết kế nhà tới chuỗi bán lẻ & E-commerce. Tập trung vào kỹ thuật đo lường, tối ưu chuyển đổi và xây hệ thống marketing có thể mở rộng.",
      quote: "Không chỉ chạy ads — tôi xây hệ thống marketing đo lường được, tối ưu được và mở rộng được. Mỗi đồng ngân sách đều có lý do; mỗi quyết định đều dựa trên dữ liệu.",
      stats: [
        { v: "55", u: "%", l: "tổng doanh thu từ Paid Media tại Trung Sơn Care" },
        { v: "9.85", u: "×", l: "ROAS — chiến dịch hiệu quả nhất" },
        { v: "168", u: "", l: "leads chất lượng / 30 ngày tại ENOCOM" },
        { v: "0", u: "", l: "vị trí SERP (featured snippet) — ngói Vạn Nam" },
      ],
      photoNote: "Thả ảnh chân dung vào đây",
    },
    pillars: {
      eyebrow: "[ 01 ] BA TRỤ NĂNG LỰC",
      title: "Dữ liệu. Hệ thống. Mở rộng.",
      sub: "Mô hình vận hành đứng sau mỗi case study trong portfolio này.",
      items: [
        {
          num: "01 / DATA",
          h: "Dữ liệu",
          p: "Lớp đo lường đặt nền trước tiên. Ghi nhận mọi tín hiệu quan trọng, lưu nơi truy vấn được, trực quan hóa các đánh đổi mà ban điều hành cần thấy.",
          tags: ["GA4", "Looker Studio", "BigQuery", "Server-side"],
        },
        {
          num: "02 / SYSTEM",
          h: "Hệ thống",
          p: "Gắn tag những thứ không gắn tag được. Khôi phục tín hiệu mất do iOS 14.5, cookie, ad-block — qua GTM Server, CAPI, Enhanced Conversion, dedupe sự kiện.",
          tags: ["GTM", "CAPI", "Enhanced Conv.", "CRO"],
        },
        {
          num: "03 / SCALE",
          h: "Mở rộng",
          p: "Khi đo lường trung thực và tag sạch, mở rộng ngân sách tự tin. Vận hành đa kênh, SEO, CRM, lịch review hiệu suất đều đặn.",
          tags: ["Paid Media", "SEO", "CRM", "Performance Ops"],
        },
      ],
    },
    cases: {
      eyebrow: "[ 02 ] CASE STUDIES",
      title: "Dự án tiêu biểu.",
      sub: "Sáu dự án. Mọi con số đều trích trực tiếp từ dashboard tôi đã trực tiếp vận hành.",
      list: [
        {
          idx: "01",
          yr: "2024 — 2025",
          ind: "Bán lẻ dược phẩm · ĐBSCL",
          name: "Trung Sơn Care",
          feature: true,
          summary: "Tái cấu trúc toàn bộ lớp đo lường bằng GTM Server (Stape.io), dedupe sự kiện qua Google + Meta + TikTok bằng Enhanced Conversion + CAPI. Paid Media hiện đóng góp 55% doanh thu với funnel quy thuộc được hoàn toàn.",
          kpis: [
            { v: "9.85", u: "×", l: "ROAS đỉnh" },
            { v: "3.04", u: "Tỷ", l: "Doanh thu (VND)" },
            { v: "−58.6", u: "%", l: "Giảm CPA" },
            { v: "55", u: "%", l: "Tỷ trọng Paid" },
          ],
          tags: ["GTM Server", "Stape.io", "CAPI", "Enhanced Conv.", "GA4", "Looker"],
          chartTitle: "ROAS · xu hướng 14 tháng",
          chart: "roas",
        },
        {
          idx: "02",
          yr: "2023 — 2024",
          ind: "Thiết kế & xây dựng nhà",
          name: "ENOCOM — 168 Leads Google Ads",
          summary: "Search + Performance Max cho bồn nước và máy nước nóng năng lượng mặt trời. Quality Score 10/10 ở từ khóa chính; 168 leads chất lượng với tỷ lệ chốt 75% trong 30 ngày.",
          kpis: [
            { v: "168", u: "", l: "Leads / 30 ngày" },
            { v: "75", u: "%", l: "Tỷ lệ chốt" },
            { v: "10", u: "/10", l: "Quality Score" },
            { v: "3.2", u: "×", l: "ROAS" },
          ],
          tags: ["Google Ads", "Search", "Performance Max", "Lead Gen"],
          chartTitle: "Conversions vs Cost",
          chart: "leads",
        },
        {
          idx: "03",
          yr: "2024",
          ind: "Thiết kế nội thất cao cấp",
          name: "ICOM Design — Meta Instant Experience",
          summary: "Xây luồng Instant Experience mobile-native trên Meta cho brief nội thất cao cấp. Catalog Remarketing + Advantage+ Shopping chạy song song với Messenger Conversions.",
          kpis: [
            { v: "4.1", u: "×", l: "ROAS" },
            { v: "−42", u: "%", l: "CPL" },
            { v: "8.7", u: "%", l: "CTR" },
          ],
          tags: ["Meta Ads", "Instant Experience", "Advantage+", "Catalog"],
          chartTitle: "Funnel · Reach → Lead",
          chart: "funnel",
        },
        {
          idx: "04",
          yr: "2023 — 2024",
          ind: "VLXD · Ngói lợp",
          name: "Vạn Nam — Top 0 SERP, ROI 300%",
          summary: "SEO + Google Ads song hành cho ngành ngói. Chiếm Top 0 (featured snippet) ở từ khóa chính và Top 1 Shopping. ROAS 168% trả về ROI 300% net.",
          kpis: [
            { v: "300", u: "%", l: "ROI" },
            { v: "168", u: "%", l: "ROAS" },
            { v: "0", u: "", l: "SERP (snippet)" },
            { v: "1", u: "", l: "Shop position" },
          ],
          tags: ["SEO", "Google Ads", "Shopping", "Featured Snippet"],
          chartTitle: "Tiến trình xếp hạng",
          chart: "rank",
        },
        {
          idx: "05",
          yr: "2023 — 2024",
          ind: "Side projects",
          name: "Ba website — tự xây & vận hành",
          summary: "Thiết kế, xây và vận hành end-to-end ba website thương hiệu — từ copywriting, IA tới deploy, gắn GA4/GTM và lịch nội dung.",
          kpis: [
            { v: "3", u: "", l: "Sites live" },
            { v: "100", u: "%", l: "Tự vận hành" },
          ],
          tags: ["WordPress", "Webflow", "GA4", "GTM", "Copy", "IA"],
          chartTitle: null,
          chart: null,
        },
      ],
    },
    method: {
      eyebrow: "[ 03 ] PHƯƠNG PHÁP",
      title: "Data-Driven Marketing.",
      sub: "Mọi engagement đều chạy cùng một loop 4 bước. Đo lường trước, mở rộng sau.",
      steps: [
        { step: "BƯỚC 01", h: "Đo lường", d: "GA4 + GTM Server. Định nghĩa event tương ứng doanh thu. Audit tag hiện hữu." },
        { step: "BƯỚC 02", h: "Khôi phục", d: "CAPI, Enhanced Conversions, dedupe server-side. Khôi phục tín hiệu mất do iOS / cookie loss." },
        { step: "BƯỚC 03", h: "Tối ưu", d: "Review bid strategy, tinh chỉnh audience, CRO landing page. Thắt chặt funnel." },
        { step: "BƯỚC 04", h: "Mở rộng", d: "Tự tin spend đa kênh Google + Meta + TikTok. Dashboard Looker review hàng tuần." },
      ],
    },
    highlights: {
      eyebrow: "[ 04 ] ĐIỂM NHẤN",
      title: "Ba con số.",
      sub: "Nếu phần còn lại không kịp đọc, đây là ba con số đáng nhớ.",
      items: [
        { tag: "TRUNG SƠN CARE", v: "9.85", u: "× ROAS", l: "3.04 Tỷ doanh thu · CPA −58.6%" },
        { tag: "ENOCOM", v: "75", u: "% chốt", l: "Quality Score 10/10 · 168 leads" },
        { tag: "VẠN NAM", v: "300", u: "% ROI", l: "Top 0 snippet · Top 1 Shopping" },
      ],
    },
    skills: {
      eyebrow: "[ 05 ] NĂNG LỰC",
      title: "Công cụ & Stack.",
      sub: "Mức thành thạo vận hành thực tế. Năm trong production, không chỉ chứng chỉ.",
      groups: [
        { cat: "Dữ liệu", items: [["GA4", 0.95], ["Looker Studio", 0.95], ["BigQuery", 0.7], ["GTM Server", 0.9]] },
        { cat: "Hệ thống", items: [["GTM", 0.95], ["Meta CAPI", 0.9], ["Enhanced Conv.", 0.9], ["Stape.io", 0.85]] },
        { cat: "Mở rộng", items: [["Google Ads", 0.95], ["Meta Ads", 0.95], ["TikTok Ads", 0.85], ["SEO Ops", 0.85]] },
        { cat: "Xây dựng", items: [["WordPress", 0.85], ["Webflow", 0.75], ["HTML/CSS", 0.8], ["Copywriting", 0.85]] },
      ],
    },
    contact: {
      eyebrow: "[ 06 ] LIÊN HỆ",
      title: "Cùng\ntrao đổi.",
      lead: "Mọi con số trong portfolio đều đến trực tiếp từ dashboard tôi vận hành. Sẵn sàng screen-share demo lúc phỏng vấn.",
      cards: [
        { lbl: "ĐIỆN THOẠI · ZALO", val: "0886.148.937", sub: "Phản hồi nhanh · Cùng số Zalo" },
        { lbl: "EMAIL", val: "sandrabruh@proton.me", sub: "Phản hồi trong 24 giờ" },
        { lbl: "VỊ TRÍ", val: "Cần Thơ · TP.HCM", sub: "Fulltime Cần Thơ · Remote linh hoạt" },
        { lbl: "PROFILE", val: "LinkedIn", sub: "Open to connect & discuss" },
      ],
      cta: "Sẵn sàng cho vai trò mới · Available 5/2026",
    },
    footer: {
      tag: "PORTFOLIO 2026 · v3.0",
      quote: "Marketing không phải nghệ thuật. Đó là kỹ thuật của những con số.",
      meta: ["LE HOANG TUAN ANH", "CẬP NHẬT · 5/2026", "DATA · SYSTEM · SCALE"],
    },
  },
};
